### ISSUE TITLE
Save of spin time update is ignored upon save due to incorrect spin date

### ISSUE THREAD

**Issue by eric-gilbertson** [RocketMan/zookeeper#158] opened 2020-06-08 04:30 UTC
Save of spin time update is ignored due to incorrect date. The issue is that the following line in playlists.track.js improperly advances the date to the following day when the spin time is adjusted:

               $("INPUT[name=edate]").val(val.toISOString().split('T')[0]); // line #305

Reproduce:
   * edit an existing playlist
   * click pencil on a spin
   * reduce spin time by 1 minute
   * click Save - time is not adjusted and log contains "update ignored message". problem is that the above javascript line advances the date to the following day so that the "in window" check fails.

**Comment by RocketMan** [comment] 2020-06-08 08:34
Hello Eric, I cannot reproduce in prod.  For me, the time is always saved as expected.

The code you reference has been in there for some time (since February), so I suspect it is hitting an edge case.

Can you point me to a playlist and specific time where the problem occurs?

**Comment by eric-gilbertson** [comment] 2020-06-08 17:25
Hi Jim,

Take a look at my 6/6/2020 show on production. I changed the Fiona Apple track time from 2:44 to 2:43. Upon save it moved from its initial position between Cohen and Ballroom Thieves to the top of the playlist because its date was advanced to 06/07/2020 (I presume that it was not rejected because this was an after the fact edit but the root issue is the same, eg the play date was advanced).

**Comment by RocketMan** [comment] 2020-06-08 17:47
Thanks Eric.  I see the problem:  All of the timestamps in that specific playlist (with the exception of the Fiona Apple track) have date 2020-06-02.  After the edit, the Fiona Apple track's date got changed to 2020-06-06 (the playlist date), which pushed it to the end of the list, as it was later than timestamps with 2020-06-02.

It looks like I need to revisit import playlist and/or edit playlist to apply some logic/correction to the track timestamps whenever the playlist date changes.  Please let me know how this specific list came to be, so I can understand the use cases better.  Thanks!

**Comment by eric-gilbertson** [comment] 2020-06-10 00:17
Yes, that makes sense. The PL was initially generated on 06/02. On Saturday I edited the PL date to 06/06. Question is what to do about this. Some possibilities include:

   * prohibit PL date change
   * retain spin date when spin time is changed
   * update spin dates when playlist date is changed

Option #1 seems draconian so my recommendation is for the latter two options.

**Comment by RocketMan** [comment] 2020-06-11 09:45
Patch has landed in prod; closing

@eric-gilbertson I've fixed your playlist from 2020-06-06.  Going forward, any playlist date or time changes should update the timestamps as expected.

**Closed by RocketMan** 2020-06-11 09:45 UTC
