### ISSUE TITLE
Warning in error log

### ISSUE THREAD

**Issue by RocketMan** [RocketMan/zookeeper#128] opened 2020-01-20 17:40 UTC
The error log in production contains frequent entries like the following:
`PHP Warning:  A non-numeric value encountered in /srv/http/zookeeper/ui/Playlists.php on line 296`
Code is here: https://github.com/RocketMan/zookeeper/blob/b10a0ff4a908a82042f0d756ff5030e726a2add7/ui/Playlists.php#L296

This is not a high priority, but it will help us more quickly resolve problems in the future by removing clutter from the log, as this message occurs quite frequently.

Also this from 'ui/Playlists::smartURL (whenever the playlist edit page is rendered):
[02-Jun-2020 23:45:22 UTC] PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in '.../zookeeper/ui/Playlists.php on line 79

**Comment by RocketMan** [comment] 2020-01-26 14:18
Note this message in the error log:
[error.log.20200125.txt](https://github.com/RocketMan/zookeeper/files/4113393/error.log.20200125.txt)

Occurs 426 times.  Harmless enough warning, but it is making log analysis more difficult.

**Comment by eric-gilbertson** [comment] 2020-06-09 04:26
Closing. Could not reproduce this locally and found no recent instances of this particular messages in the production log files.

**Comment by RocketMan** [comment] 2020-06-09 08:10
````[Mon Jun 08 11:07:47.721830 2020] [php7:warn] [pid 30867] [client 54.87.252.111:14800] PHP Warning:  A non-numeric value encountered in /srv/http/zookeeper/ui/Playlists.php on line 317
[Mon Jun 08 11:07:58.414749 2020] [php7:warn] [pid 30707] [client 54.87.252.111:17430] PHP Warning:  A non-numeric value encountered in /srv/http/zookeeper/ui/Playlists.php on line 317
[Mon Jun 08 11:08:03.795876 2020] [php7:warn] [pid 30867] [client 54.87.252.111:18738] PHP Warning:  A non-numeric value encountered in /srv/http/zookeeper/ui/Playlists.php on line 317
[Mon Jun 08 12:40:13.910712 2020] [php7:warn] [pid 31169] [client 46.229.168.131:30324] PHP Warning:  A non-numeric value encountered in /srv/http/zookeeper/ui/Playlists.php on line 317
[Mon Jun 08 12:51:51.246787 2020] [php7:warn] [pid 31335] [client 46.229.168.135:32104] PHP Warning:  A non-numeric value encountered in /srv/http/zookeeper/ui/Playlists.php on line 317
[Mon Jun 08 23:05:41.247223 2020] [php7:warn] [pid 2089] [client 77.88.5.18:44210] PHP Warning:  A non-numeric value encountered in /srv/http/zookeeper/ui/Playlists.php on line 317
````

**Comment by eric-gilbertson** [comment] 2020-06-10 00:06
I don't see these in my logs. Please provide steps to reproduce and/or the name of the log file in which they appear.

**Comment by eric-gilbertson** [comment] 2020-06-10 01:44
I did find another, unrelated spurious log message when looking at this, eg using '{}' to deference arrays. Added it to this ticket rather than creating a new ticket for it.

**Comment by RocketMan** [comment] 2020-06-10 09:06
> I don't see these in my logs. Please provide steps to reproduce and/or the name of the log file in which they appear.

It is in the error log.  In prod, that is /var/log/apache2/error.log.

**Comment by RocketMan** [comment] 2020-06-11 09:38
The curly braces warning is new to PHP 7.4 which is why we don't see it in prod.  It's good that you are finding and fixing these sorts of warnings.  PHP is notorious for breaking things with new releases.  Some apps refuse to run on versions of PHP that are too *new*.  We don't want zk to be one of those apps.

Looking into the non-int warning, it's because of legacy data in prod.  A very long time ago (more than 18 years ago in fact), `showtime` was a free-form text field.  A clue to this is in the method `timeToAMPM` which performs a basic check before parsing the field.  I suspect bots are hitting the old playlists as they scan the site.

You can make the warning go away by replacing `makeShowDateAndTime` in ui/Playlists.php with something like this:
````
    public static function makeShowDateAndTime($row) {
        return self::timestampToDate($row['showdate']) . " " . self::timeToAMPM($row['showtime']);
    }
````

timeToAMPM does the right thing, so is safe to use.  The functions `showStartTime` and `showEndTime` can then be removed.  As far as I can tell, `makeShowDateAndTime` is the only code path that generates this warning.

**Closed** 2021-02-17 18:36 UTC
